export const vesselTypeOptions = {
    'Bulk Carrier': 'BULK_CARRIER',
    'Container': 'CONTAINER',
    'Crude Oil': 'CRUDE_OIL',
    'Product Oil': 'PRODUCT_OIL',
    'LPG (Liquefied Petroleum Gas)': 'LPG',
    'LNG (Liquefied Natural Gas)': 'LNG',
    'Reefer': 'REEFER',
    'Ro-Ro (Roll-On/Roll-Off)': 'RO_RO',
    'General Cargo': 'GENERAL_CARGO',
    'Cruise': 'CRUISE',
    'Ferry': 'FERRY',
    'Ocean Liner': 'OCEAN_LINER',
    'Catamaran': 'CATAMARAN',
    'Motor Yacht': 'MOTOR_YACHT',
    'Sailing Yacht': 'SAILING_YACHT',
    'Mega Yacht': 'MEGA_YACHT',
    'Explorer Yacht': 'EXPLORER_YACHT',
    'Sport Fishing Yacht': 'SPORT_FISHING_YACHT',
  };
  
  export const rankOptions = {
    'Master/Captain': 'CAPTAIN',
    'Chief Officer': 'CHIEF_OFFICER',
    'First Officer': 'FIRST_OFFICER',
    'Second Officer': 'SECOND_OFFICER',
    'Third Officer': 'THIRD_OFFICER',
    'Deck Cadet': 'DECK_CADET',
    'Chief Engineer': 'CHIEF_ENGINEER',
    'First Engineer': 'FIRST_ENGINEER',
    'Second Engineer': 'SECOND_ENGINEER',
    'Third Engineer': 'THIRD_ENGINEER',
    'Fourth Engineer': 'FOURTH_ENGINEER',
    'Electro-Technical Officer': 'ELECTRO_TECHNICAL_OFFICER',
    'Boatswain': 'BOATSWAIN',
    'Able Seaman': 'ABLE_SEAMAN',
    'Ordinary Seaman': 'ORDINARY_SEAMAN',
    'Chief Steward': 'CHIEF_STEWARD',
    'Steward': 'STEWARD',
    'Messman': 'MESSMAN',
    'Fitter': 'FITTER',
    'Pumpman': 'PUMPMAN',
    'Cook': 'COOK',
    'Motorman': 'MOTORMAN',
    'Oiler': 'OILER',
    'Welder': 'WELDER',
    'Refrigeration Engineer': 'REFRIGERATION_ENGINEER',
    'Trainee Officer': 'TRAINEE_OFFICER',
    'Radio Officer/Radio Operator': 'RADIO_OFFICER',
  };
  